# Generated by Django 4.2.6 on 2023-11-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewerx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comment', to='reviewerx.comment'),
        ),
        migrations.AlterField(
            model_name='review',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='review', to='reviewerx.reviewlike'),
        ),
        migrations.DeleteModel(
            name='BusinessAverageRating',
        ),
    ]
