# Generated by Django 4.2.6 on 2023-11-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewerx', '0002_alter_review_comments_alter_review_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewlike',
            name='review_id',
        ),
        migrations.RemoveField(
            model_name='reviewphoto',
            name='review_id',
        ),
        migrations.AddField(
            model_name='review',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='review_photo', to='reviewerx.reviewphoto'),
        ),
    ]
