# Generated by Django 4.2.6 on 2023-11-06 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewerx', '0003_remove_reviewlike_review_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='review_id',
        ),
        migrations.RemoveField(
            model_name='commentlike',
            name='comment_id',
        ),
        migrations.RemoveField(
            model_name='commentphoto',
            name='comment_id',
        ),
    ]
