# Generated by Django 4.2.6 on 2023-11-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewerx', '0005_businesstype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='photos',
            field=models.ManyToManyField(blank=True, null=True, related_name='businesses', to='reviewerx.businessphoto'),
        ),
    ]
