# Generated by Django 4.2.6 on 2023-11-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewerx', '0006_alter_business_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='reviews',
            field=models.ManyToManyField(blank=True, null=True, related_name='businesses', to='reviewerx.review'),
        ),
    ]
