INSERT INTO
    reviewerx_businesstype (name)
VALUES
    ("4WD, ATV & Off-Road Tours"),
    ("Adrenaline & Extreme Tours"),
    ("Air Tours"),
    ("Airport Lounges"),
    ("Antique Stores"),
    ("Aquariums"),
    ("Arab Baths"),
    ("Archaeology Tours"),
    ("Architectural Buildings"),
    ("Arenas & Stadiums"),
    ("Art Galleries"),
    ("Art Museums"),
    ("Auto Race Tracks"),
    ("Ballets"),
    ("Balloon Rides"),
    ("Bar, Club & Pub Tours"),
    ("Bars & Clubs"),
    ("Battlefields"),
    ("Beach & Pool Clubs"),
    ("Beaches"),
    ("Beer Tastings & Tours"),
    ("Bike Tours"),
    ("Biking Trails"),
    ("Blues Clubs & Bars"),
    ("Boat Rentals"),
    ("Boat Tours"),
    ("Bodies of Water"),
    ("Bowling Alleys"),
    ("Breweries"),
    ("Bridges"),
    ("Bus Tours"),
    ("Bus Transportation"),
    ("Cabarets"),
    ("Canyoning & Rappelling Tours"),
    ("Canyons"),
    ("Casinos"),
    ("Castles"),
    ("Caverns & Caves"),
    ("Cemeteries"),
    ("Children's Museums"),
    ("Churches & Cathedrals"),
    ("Cigar Bars"),
    ("Cirque du Soleil Shows"),
    ("City Tours"),
    ("Civic Centers"),
    ("Climbing Tours"),
    ("Coffee & Tea Tours"),
    ("Coffeehouses"),
    ("Comedy Clubs"),
    ("Concerts"),
    ("Conference & Convention Centers"),
    ("Cooking Classes"),
    ("Country & Western Bars"),
    ("Cross-country Ski Areas"),
    ("Cultural Events"),
    ("Cultural Tours"),
    ("Dams"),
    ("Dance Clubs & Discos"),
    ("Day Trips"),
    ("Department Stores"),
    ("Deserts"),
    ("Dinner Theaters"),
    ("Distilleries"),
    ("Distillery Tours"),
    ("Dog Tracks"),
    ("Dolphin & Whale Watching"),
    ("Duck Tours"),
    ("Eco Tours"),
    ("Equestrian Trails"),
    ("Exhibitions"),
    ("Factory Outlets"),
    ("Factory Tours"),
    ("Farmers Markets"),
    ("Farms"),
    ("Fashion Shows & Tours"),
    ("Ferries"),
    ("Fishing Charters & Tours"),
    ("Flea & Street Markets"),
    ("Food & Drink Festivals"),
    ("Food Tours"),
    ("Forests"),
    ("Fountains"),
    ("Game & Entertainment Centers"),
    ("Gardens"),
    ("Gay Clubs & Bars"),
    ("Gear Rentals"),
    ("Geologic Formations"),
    ("Ghost & Vampire Tours"),
    ("Ghost Towns"),
    ("Gift & Specialty Shops"),
    ("Golf Courses"),
    ("Gondola Cruises"),
    ("Government Buildings"),
    ("Hammams & Turkish Baths"),
    ("Health/Fitness Clubs & Gyms"),
    ("Helicopter Tours"),
    ("Hiking & Camping Tours"),
    ("Hiking Trails"),
    ("Historic Sites"),
    ("Historic Walking Areas"),
    ("Historical & Heritage Tours"),
    ("History Museums"),
    ("Hop-On Hop-Off Tours"),
    ("Horse Tracks"),
    ("Horse-Drawn Carriage Tours"),
    ("Horseback Riding Tours"),
    ("Hot Springs & Geysers"),
    ("Hotel"),
    ("Islands"),
    ("Jazz Clubs & Bars"),
    ("Jogging Paths & Tracks"),
    ("Karaoke Bars"),
    ("Kayaking & Canoeing"),
    ("Lessons & Workshops"),
    ("Libraries"),
    ("Lighthouses"),
    ("Literary, Art & Music Tours"),
    ("Lookouts"),
    ("Luaus"),
    ("Marinas"),
    ("Mass Transportation Systems"),
    ("Military Bases & Facilities"),
    ("Military Museums"),
    ("Mines"),
    ("Mini Golf"),
    ("Monuments & Statues"),
    ("Motorcycle Tours"),
    ("Motorcycle Trails"),
    ("Mountains"),
    ("Movie & TV Tours"),
    ("Movie Theaters"),
    ("Multi-day Tours"),
    ("Music Festivals"),
    ("Mysterious Sites"),
    ("National Parks"),
    ("Natural History Museums"),
    ("Nature & Wildlife Areas"),
    ("Nature & Wildlife Tours"),
    ("Neighborhoods"),
    ("Night Tours"),
    ("Observation Decks & Towers"),
    ("Observatories & Planetariums"),
    ("Off-Road & ATV Trails"),
    ("Onsen Resorts"),
    ("Operas"),
    ("Paint & Pottery Studios"),
    ("Parasailing & Paragliding"),
    ("Parks"),
    ("Performances"),
    ("Photography Tours"),
    ("Piano Bars"),
    ("Piers & Boardwalks"),
    ("Playgrounds"),
    ("Points of Interest & Landmarks"),
    ("Private Tours"),
    ("Rail Tours"),
    ("Railways"),
    ("Ranches"),
    ("Reefs"),
    ("Rental"),
    ("Restaurant"),
    ("River Rafting & Tubing"),
    ("Roman Baths"),
    ("Room Escape Games"),
    ("Running Tours"),
    ("Sacred & Religious Sites"),
    ("Safaris"),
    ("Scavenger Hunts"),
    ("Scenic Drives"),
    ("Scenic Railroads"),
    ("Scenic Walking Areas"),
    ("Science Museums"),
    ("Scuba & Snorkeling"),
    ("Seasonal Fireworks"),
    ("Segway Tours"),
    ("Self-Guided Tours & Rentals"),
    ("Shark Diving"),
    ("Ships"),
    ("Shooting Ranges"),
    ("Shopping Malls"),
    ("Shopping Tours"),
    ("Sightseeing Tours"),
    ("Ski & Snow Tours"),
    ("Ski & Snowboard Areas"),
    ("Skydiving"),
    ("Spas"),
    ("Specialty Museums"),
    ("Speed Boats Tours"),
    ("Sporting Events"),
    ("Sports Complexes"),
    ("Stand-Up Paddleboarding"),
    ("State Parks"),
    ("Submarine Tours"),
    ("Surfing, Windsurfing & Kitesurfing"),
    ("Swim with Dolphins"),
    ("Symphonies"),
    ("Taxis & Shuttles"),
    ("Theaters"),
    ("Theme Parks"),
    ("Thermal Spas"),
    ("Tramways"),
    ("Universities & Schools"),
    ("Valleys"),
    ("Vespa, Scooter & Moped Tours"),
    ("Visitor Centers"),
    ("Volcanos"),
    ("Walking Tours"),
    ("Water Parks"),
    ("Water Sports"),
    ("Waterfalls"),
    ("Waterskiing & Jetskiing"),
    ("Wedding Chapels"),
    ("Wine Bars"),
    ("Wine Tours & Tastings"),
    ("Wineries & Vineyards"),
    ("Yoga & Pilates"),
    ("Zipline & Aerial Adventure Parks"),
    ("Zoos");